### ISSUE TITLE
Horizontal scroll bar appears in the navigation bar with firefox.

### ISSUE THREAD

**Issue by GeorgeBrown128** [yoshiharuyamashita/blackburn#13]
Thank you for the theme, it has proved excellent so far!
The title says it all really. I tested with Firefox 46.0 on both Windows and Ubuntu Linux, and a scroll bar appears in the bottom left of the page, the width of the navigation bar.
The issue doesn't appear to be present with Chrome or Internet Explorer

**Comment by yoshiharuyamashita** [comment]
Hi @GeorgeBrown128 

Thanks for reporting. I can reproduce it at my end. I will take a look.

Cheers

Yoshi

**Comment by GeorgeBrown128** [comment]
Updated, and all seems fine on my end too now. Thank you very much!

**Comment by yoshiharuyamashita** [comment]
Glad to hear it, cheers!
