### ISSUE TITLE
Menu not working on small screens

### ISSUE THREAD

**Issue by tfgordon** [yoshiharuyamashita/blackburn#20]
I really like your blackburn Hugo theme and am trying to use it.  But for some reason the pull-down menu is not working for my site, when viewed on my Android phone.  Oddly, your demo site is working.  Any idea what the problem might be?  You can try my site at http://www.tfgordon.de to see the problem.

**Comment by yoshiharuyamashita** [comment]
Hi @tfgordon 

On your site you have:

<script src="https://tfgordon.github.iojs/ui.js"></script>

Perhaps you meant it to be:

<script src="https://tfgordon.github.io/js/ui.js"></script>

I hope this helps.

Yoshi

**Comment by yoshiharuyamashita** [comment]
Oops...

`<script src="https://tfgordon.github.iojs/ui.js"></script>`

to

`<script src="https://tfgordon.github.io/js/ui.js"></script>`

**Comment by tfgordon** [comment]
Many thanks.  Simply adding a "/" at the end of the  baseurl in the in config.toml file fixed the problem.  Thanks also for your very nice Hugo template.  One small suggestion:  Would it be possible to have URL links be clickable also in the summary descriptions of articles, in list views? Or can the template be configured to do this?

________________________________

**Comment by yoshiharuyamashita** [comment]
You are very welcome. I am glad you like it :)

> Would it be possible to have URL links be clickable also in the summary descriptions of articles, in list views?

If I understand this correctly you can use:

`<!--more-->`

in your markdown posts.

See [here](https://raw.githubusercontent.com/yoshiharuyamashita/yoshiharuyamashita.com/master/content/post/grillstock-festival-july-2016.md) as an example. The "Grillstock Festival" text is rendered as a link rather than plain text.

More info [here](https://gohugo.io/content/summaries/).

**Comment by tfgordon** [comment]
Thank you but that is not exactly what I meant.  I would like anchors to be clickable in the part of the text which appears before  when shown in list views, not only in the view of a single post.
To see the problem, take a look at my blog at:

http://www.tfgordon.de/

In the second item, with the title "Slides of my 2007 ICAIL Keynote Address", the "PDF" and "OpenDocument" are not clickable, to download the files.  You have to first click on the title of the article, to display the article in a separate view.  Only then are the PDF and OpenDocument links are shown highlighted in blue and can be clicked upon.  It would be nice if the reader did not have to first click on the title of the article to follow these links.  Or even to know that they are links.

________________________________

**Comment by yoshiharuyamashita** [comment]
I am using Markdown to generate my page and if I have something like:

`+++
date = "2016-07-17T15:15:13+01:00"
description = "blah"
draft = false
tags = ["blah", "blah blah"]
title = "blah"
topics = ["blah"]

+++

Just a [test](https://www.google.co.uk/).

`

Then the test string is clickable in the summary.

**Comment by tfgordon** [comment]
OK.  Thank you.  That helped.  I got it working now.  It seems the  is required for the links to work.  I wrongly thought that  was only a hint to suggest where to break the front matter when displaying the article in lists.
________________________________

**Comment by yoshiharuyamashita** [comment]
Glad it helped. Closing this issue now.
