### ISSUE TITLE
How to remove "post" from URLs

### ISSUE THREAD

**Issue by braimee** [yoshiharuyamashita/blackburn#29]
Hey there,

I'm looking to migrate my existing Ghost site to Hugo, and I'd love to use your them.  My existing page naming structure is http://domain/name-of-post.  In my test lab I've migrated Ghost to Hugo and turned on your theme, and now all my posts have a convention of http://domain**/post/**name-of-post.  What config change can I make to snip out the **/post** from the URL scheme?

Thanks!
Brian

**Comment by yoshiharuyamashita** [comment]
Hi @braimee 

Thanks for your message.

I have not tried this myself but does this help?

[Permalinks](http://gohugo.io/extras/permalinks/)

Maybe you can do something like:

`[permalinks]
    post = "/:title"`

?

**Comment by yoshiharuyamashita** [comment]
I have tried specifying

`[permalinks]`
`post = "/:title"`

in my config and

http://domain/post/name-of-post/

is now rendered as

http://domain/name-of-post/

(not sure how to get rid of the last "/" I am afraid)

**Comment by braimee** [comment]
That seemed to do it thanks!
