### ISSUE TITLE
baseurl not correct in footer.html

### ISSUE THREAD

**Issue by ronsmits** [yoshiharuyamashita/blackburn#35]
I have in config.toml: `baseurl = "https://ronsmits.org"` the generated code in footer.html tries to load `https://ronsmits.orgjs/ui.js`. 

changed `<script src="{{ .Site.BaseURL }}js/ui.js"></script>` into `<script src="{{ .Site.BaseURL }}/js/ui.js"></script>`

**Comment by yoshiharuyamashita** [comment]
Please make sure to end baseurl with a '/'.
