### ISSUE TITLE
Customize Dates

### ISSUE THREAD

**Issue by 3835** [yoshiharuyamashita/blackburn#36]
Hi!
I would like customize dates on Blackburn theme based on tutorial form Hugo official site (Tutorial/Multilingual Site -> http://gohugo.io/tutorials/create-a-multilingual-site/) Where I'm find in Blackburn part of the code responsible for displaying the date post?
Sorry for silly question, but I'm noob on HTML world 
Thanks for great theme!

**Comment by 3835** [comment]
I find! 
`blackburn/layouts/partials/post_meta.html`
Sorry for disturb:)

**Comment by yoshiharuyamashita** [comment]
Glad it's sorted!
