### ISSUE TITLE
Removing RSS field from sidebar

### ISSUE THREAD

**Issue by sjfox** [yoshiharuyamashita/blackburn#41]
Hi There,

Thank you so much for this wonderful theme! It's exactly what I was looking for for my personal website. I was wondering if you could help me fix one issue I'm having with it. I'd like to remove the RSS feed button from the website sidebar, but can't find any place in the code that this is specified. Could you point me in the right direction?

Thank you,
Spencer

**Comment by yoshiharuyamashita** [comment]
Hi @sjfox 

I'm glad you like it!

The RSS link is in:

../layouts/partials/social.html

So you should be able to override it by creating your version of social.html (e.g. without RSS) and put it to your site's layouts/partials/ directory.

I hope this helps.

**Comment by sjfox** [comment]
Thank you so much, this worked perfectly!

Best wishes,
-Spencer




On Apr 20, 2017, at 05:42, Yoshiharu Yamashita <notifications@github.com> wrote:

Hi @sjfox <https://github.com/sjfox>
I'm glad you like it!

The RSS link is in:

../layouts/partials/social.html

So you should be able to override it by creating your version of social.html (e.g. without RSS) and put it to your site's layouts/partials/ directory.

I hope this helps.
