### ISSUE TITLE
not summaries

### ISSUE THREAD

**Issue by pawal** [yoshiharuyamashita/blackburn#42]
Hi,

I am looking into converting a Wordpress blog into Hugo, and found your very good theme.

However, it seems that I can't remove the "read more" (with summary texts) from the blog entries, is there a way to display the full posts? Another them I tried I could change the param truncate to false to fix this, is this possible with blackburn?

Thanks,
Patrik

**Comment by yoshiharuyamashita** [comment]
Apologies for not coming back to you sooner. I see from your pull request that you've now sorted the issue.

Thanks @pawal
