### ISSUE TITLE
Support for bitcoin Links

### ISSUE THREAD

**Issue by Linuturk** [yoshiharuyamashita/blackburn#49]
I'm attempting to add a Donate Main Menu option to the sidebar.

```
  [[menu.main]]                                                                 
    name = "Donate"                                                             
    pre = "<i class='fa fa-btc fa-fw'></i>"                                     
    weight = 6                                                                  
    identifier = "bitcoin"                                                      
    url = "bitcoin:1FkKq8MSLuBMcE6NfvZ4qLhAYK6auTthTM"
```

Unfortunately, this seems to be parsed down to:
```
<a class="pure-menu-link" href="#ZgotmplZ"><i class="fa fa-btc fa-fw"></i>Donate</a>
```

Instead of something valid like:
```
<a class="pure-menu-link" href="bitcoin:1FkKq8MSLuBMcE6NfvZ4qLhAYK6auTthTM"><i class="fa fa-btc fa-fw"></i>Donate</a>
```

Any tips here?

**Comment by yoshiharuyamashita** [comment]
Hi @Linuturk 

I haven't tried this but perhaps you override partials/sidemenu.html

and apply `safeHTMLAttr` to `{{ .URL }}` in that file?

See [here](https://gohugo.io/functions/safehtmlattr/) for more information.

**Comment by Linuturk** [comment]
Looks like changing it to:

```
<a class="pure-menu-link" {{ printf "href=%q" .URL | safeHTMLAttr }}>{{ .Pre }}{{ .Name }}</a>
```

Works. Would you like a PR to update the template?

**Comment by jhabdas** [comment]
@Linuturk @yoshiharuyamashita Before I do, have either of you considered bringing this up in the Hugo Discussion forums for a clean implementation as opposed to a hack? It seems the type of Joe that'd be using Hugo right now is the same kind of Joe that would want to receive money using cryptos.

**Comment by Linuturk** [comment]
I haven't brought it up to the hugo developers. Feel free to do so, and let me know the issue so I can chime in. Thanks! @jhabdas

**Comment by jhabdas** [comment]
@Linuturk For sure bud. I was ripping through the new docs site (isn't it awesome?) yesterday and saw the approach used here is the one suggested in the docs. I'd raise it in the discussion forum but I just raised some other issues which seem more important to me right now and don't want to generate too much noise all at once. Once I swoop back to add some bitcoin links I'll be sure to raise something in the forums and will try to remember to ping ya when I do. Cheers!
