### ISSUE TITLE
There is something wrong with highlighting the Golang Markdown

### ISSUE THREAD

**Issue by usayao** [yoshiharuyamashita/blackburn#54]
There is something wrong with highlighting the Golang Markdown
example
```go
 var s string
fmt.Println("hello")
```
or
```golang
 var s string
fmt.Println("hello")
```

Cannot display normally！

**Comment by yoshiharuyamashita** [comment]
@usayao 

Please could you post a link to a page showing the problem?

Cheers

**Comment by usayao** [comment]
https://usayao.github.io/post/代码高亮测试/

发自我的 iPhone

在 2017年9月6日，00:50，Yoshiharu Yamashita <notifications@github.com<mailto:notifications@github.com>> 写道：


@usayao<https://github.com/usayao>

Please could you post a link to a page showing the problem?

Cheers

**Comment by usayao** [comment]
highlight.js  default unsupported Golang

**Comment by yoshiharuyamashita** [comment]
Try adding:

`highlightjs_extra_languages = ["go"]`

in your `[params]` section of your config file.

**Comment by usayao** [comment]
Thank you

在 2017年9月6日，18:25，Yoshiharu Yamashita <notifications@github.com<mailto:notifications@github.com>> 写道：


Try adding:

highlightjs_extra_languages = ["go"]

in your [params] section of your config file.
