### ISSUE TITLE
Why I can't see tags and categories ? 

### ISSUE THREAD

**Issue by imroc** [yoshiharuyamashita/blackburn#55]
I added this to the head of my md:
```
+++
title = "Hi"
date = 2017-09-05T22:46:02+08:00
tqgs = ["tag1","tag2"]
categories = ["golang","github"]
draft =  true
+++
```

**Comment by yoshiharuyamashita** [comment]
@imroc 

`tqgs` -> typo perhaps?

```
tags = ["tag1", "tag2"]
topics = ["topic1", "topic2"]
```

should work.

**Comment by imroc** [comment]
yeah, you're right, I can see tags and topics in the blog. But it still not displayed on the left side like this:
![image](https://user-images.githubusercontent.com/7448852/30087981-6695f0a2-92d6-11e7-8b7c-0873f49e7171.png)

how can I do it?

**Comment by yoshiharuyamashita** [comment]
Are they defined in your site config file?

Have a look at my [site config](https://github.com/yoshiharuyamashita/yoshiharuyamashita.com/blob/master/config.toml).

```
  [[menu.main]]
    name = "Topics"
    pre = "<i class='fa fa-folder fa-fw'></i>"
    weight = 3
    identifier = "topic"
    url = "/topics/"
  [[menu.main]]
    name = "Tags"
    pre = "<i class='fa fa-tags fa-fw'></i>"
    weight = 4
    identifier = "tag"
    url = "/tags/"
```
