### ISSUE TITLE
some browser blocked pure-css when site deployed as HTTPS

### ISSUE THREAD

**Issue by xusiwei** [yoshiharuyamashita/blackburn#6]
in layouts/partials/head.html, the Pure-CSS refs as HTTP:
`<link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/pure-min.css">`

but on some browser, likes firefox, blocks it by default. 

https://developer.mozilla.org/en-US/docs/Security/Mixed_content/How_to_fix_website_with_mixed_content

**Comment by yoshiharuyamashita** [comment]
@xusiwei

Thanks for reporting and providing the link.

I've made changes so that the PureCSS files are served from "https://cdnjs.cloudflare.com/ajax/libs/pure/..."

Ref: 33fb355

**Comment by xusiwei** [comment]
@yoshiharuyamashita , thanks for your solution :-)

**Comment by xusiwei** [comment]
@yoshiharuyamashita  by the way, you can write `fix #6` in commit message,  GitHub will recognized it and close `#6` automatically after your push. :-)

**Comment by yoshiharuyamashita** [comment]
Thanks for the tip! I'm still new to GitHub.
