### ISSUE TITLE
hugo v0.32.4 works fine serving /post/ directory, not v0.35, not v0.36 

### ISSUE THREAD

**Issue by nonumeros** [yoshiharuyamashita/blackburn#65]
Yoshiharu, can you check https://nonumeros.github.io 

`This XML file does not appear to have any style information associated with it. The document tree is shown below`

**Comment by nonumeros** [comment]
Let's assume v0.36 is running. If you were to rename **li.html** to **list.html** on `/layouts/_default/ directory, then at least the links show. Furthermore if you were to replace the contents of that file for say

     <li class="posts">
     {{ range .Data.Pages -}}
       <li>
         <span><a href="{{ .Permalink }}">{{ .Title }}</a> <a class="pure-menu-has-children">{{ .Date.Format "Mon, Jan 2, 2006" }}</a></span>
       </li>
     </li>
     {{- end }}
     
things get better. But I wouldn't know what to do from there

**Comment by yoshiharuyamashita** [comment]
Hi @nonumeros 

I can reproduce the problem at my end. I'm not sure what's going on but will take a look at it as soon as I can.

**Comment by HEDAS** [comment]
I meet the same problem. This problem also appears in the demo site.

**Comment by nonumeros** [comment]
@yoshiharuyamashita appreciate it. @HEDAS thanks for confirming it. 

Your can reproduce the same problem with https://github.com/tummychow/lanyon-hugo

**Comment by nonumeros** [comment]
I'm closing the issue. Some of the contributors at the Hugo community do not offer constructive solutions and/or helpful feedback to the problem.

**Comment by jaketothepast** [comment]
@nonumeros @yoshiharuyamashita Not sure how much investigating has been done but it looks like when hugo builds the site index.html never gets generated. Looking into it currently. I too am having the /post/ serving issue

**Comment by jaketothepast** [comment]
Found the issue guys, here, in the notes section for release 0.33: https://gohugo.io/news/0.33-relnotes/. They removed indexes from the template lookup system, so layouts/indexes/post was never getting rendered. I am able to fix this issue by moving the post.html template into the post directory, unless there is a better place for it. I will submit a PR as well.

**Comment by nonumeros** [comment]
@jaketothepast awesome job. 

If you can initialize a pull request also for https://github.com/tummychow/lanyon-hugo some of the folks using it, will appreciate it. Briefly testing that theme with the v0.37-dev looks as if - based on your research - a post directory would have to be created with the post.html file from indexes directory, moved into it.

**Comment by jaketothepast** [comment]
Thank you! And sure will do. Also for reference I tested my pull request to this repository with Hugo v0.36 on Windows. #66

**Comment by jaketothepast** [comment]
until @yoshiharuyamashita merges this feel free to use my fork: https://github.com/jaketothepast/blackburn

**Comment by parthpunkster** [comment]
I am still facing this issue, is the issue resolved?

**Comment by nonumeros** [comment]
Yes with https://github.com/yoshiharuyamashita/blackburn/commit/579beef9efded29b6cb83eda74ff98a82ba9ce0c

If you're referring to your hugo site... It seems you removed `post.html` from the layouts/post directory at https://github.com/parthpunkster/parthpunkster-hugo/tree/master/themes/blackburn/layouts/post
