### ISSUE TITLE
When I click the Posts, my articles don't appear

### ISSUE THREAD

**Issue by fengberlin** [yoshiharuyamashita/blackburn#69]
When I click the Posts, my articles don't appear. How can I show my all articles in the page Posts?

**Comment by mostafa-asg** [comment]
I have the same problem too, my posts are in :
content/post folder
Example:
content/post/first-post.md

**Comment by mostafa-asg** [comment]
I solved the issue. I used "hugo 0.31.1" and when I upgrade to the latest version, it shows my post.

**Comment by fengberlin** [comment]
So far, my version is also 0.37.1. I just decide to delete my theme and git clone again, and I delete my repo too...
