### ISSUE TITLE
Customize Theme

### ISSUE THREAD

**Issue by benny-noh** [yoshiharuyamashita/blackburn#7]
Hi Yoshi I can not find any contact info so I am writing my "issue" here. I would like to create a new section for tutorials and one for scripts. but I don't find the place to get the new section working in the menu. do you have a solution how to do this? you are welcome to contact me by email to discuss this

**Comment by yoshiharuyamashita** [comment]
I've followed the section titled "Which Template will be rendered?" here:

https://gohugo.io/templates/content/

So perhaps you could create

"..\YourSite\layouts\section\tutorial.html"

then add something like this in your config.toml:

>   [[menu.main]]
>     name = "Tutorials"
>     pre = "your icon here"
>     weight = 4
>     identifier = "tutorial"
>     url = "/tutorial/"

You can repeat the same steps for your "Scripts" section.

Does this work for you? I'll give it a go at my end when I get a chance.

Cheers!

Yoshi

**Comment by benny-noh** [comment]
Hi Yoshi,

I will test this as soon as possible. Will report you. Thanks for your help
so far.

Greets,
Benjamin
Am 24.02.2016 11:19 schrieb "Yoshiharu Yamashita" <notifications@github.com

**Comment by benny-noh** [comment]
Hi Yoshi,

I added the described folders to my site and copied the post/single.html to
the section folder but it was not rendered now. Do I have to specify some
tags so that tutorial section is recognized.

Greets,
Benjamin
Am 24.02.2016 11:19 schrieb "Yoshiharu Yamashita" <notifications@github.com

**Comment by yoshiharuyamashita** [comment]
Hi Benjamin

> I added the described folders to my site and copied the post/single.html to
> the section folder 

So do you now have "YourSite\layouts\section\single.html"?

If so try renaming "single.html" to "tutorial.html" and see if that works.

Cheers

Yoshi

**Comment by benny-noh** [comment]
Yes exactly. Tried renaming but still a blank page when clicking on
tutorial link in menu

Cheers
Am 24.02.2016 13:25 schrieb "Yoshiharu Yamashita" <notifications@github.com

**Comment by yoshiharuyamashita** [comment]
OK, I've done a quick test.

I've created:

"..\exampleSite\layouts\section\tutorial.html"

Also I've generated my dummy tutorial content in here:

"..\exampleSite\content\tutorial\tutorial-1.md"

I've added the following:

```
  [[menu.main]]
    name = "Tutorials"
    pre = "<i class='fa fa-phone fa-fw'></i>"
    weight = 4
    identifier = "tutorial"
    url = "/tutorial/"
```

to the exampleSite's config.toml.

When I run "hugo server" and click on the Tutorials link, the page shows its content for me.

**Comment by benny-noh** [comment]
Ah I used not section for the folder name I used "tutorial" will tests this
in a few minutes
Am 24.02.2016 13:38 schrieb "Yoshiharu Yamashita" <notifications@github.com

**Comment by benny-noh** [comment]
Getting this

ERROR: 2016/02/24 13:45:10 general.go:222: Error while rendering section
tutorial: template: section/tutorial.html:11:5: executing
"section/tutorial.html" at <.Content>: Content is not a field of struct
type *hugolib.Node

Can you tell me the content of your template.html?

Cheers
Am 24.02.2016 13:38 schrieb "Yoshiharu Yamashita" <notifications@github.com

**Comment by yoshiharuyamashita** [comment]
Ah I wasn't using 

> {{ .Content }}

in my tutorial.html file. If I do, I get the same error as you. I'll need to investigate what's going on.

Yoshi

**Comment by benny-noh** [comment]
Okay when I remove `{{ .Content }}` the site renders but the Content is missing for sure ;) does not need to be fixed quickly, so no stress with it ;)

**Comment by benny-noh** [comment]
Is it possible to replace the `{{ .Content }}` with your code to display the content?

**Comment by yoshiharuyamashita** [comment]
Hi Benjamin

As far as I understand, I think you need:

**1 "YourSite\layouts\section\tutorial.html"** - in this file you can't use {{ .Content }} (you could customise "\blackburn\layouts\indexes\post.html" to create your tutorial.html).

[Content List Template](https://gohugo.io/templates/list/)

> List pages are of the type "node" and have all the node variables and site variables available to use in the templates.

**2 "YourSite\layouts\tutorial\single.html"** - in this file you can use {{ .Content }} (you could customise "\blackburn\layouts\post\single.html" for this).

[Single Content Template](https://gohugo.io/templates/content/)

> Content pages are of the type "page" and have all the page variables and site variables available to use in the templates.

I think this file is optional as if it were missing, "YourSite\themes\blackburn\layouts\_default\single.html" would be used.

Take a look at https://github.com/spf13/spf13.com for example. In spf13's case, "project" is equivalent to your "tutorial" or "script".

He has:

- spf13.com/layouts/section/project.html // No use of {{ .Content }}
- spf13.com/layouts/project/single.html // {{ .Content }} is used here

So I think you can model your site just like this.

I hope this helps.

Yoshi

**Comment by benny-noh** [comment]
Really nice =) this works great for me =) doesn't need to change the files, just working now =)
