### ISSUE TITLE
Can blackburn counts web traffic by busuanzi?

### ISSUE THREAD

**Issue by shelbylee** [yoshiharuyamashita/blackburn#70]
need help!
I want to count my site's page views, but I didn't find any related param in blackburn.

**Comment by yoshiharuyamashita** [comment]
Hi @shelbylee 

Unfortunately the Blackburn theme does not support this right now. Looking at this [theme](https://github.com/olOwOlo/hugo-theme-even/blob/master/exampleSite/config.toml), it looks fairly simple to add though.

**Comment by shelbylee** [comment]
@yoshiharuyamashita okay, thanks a lot~
