### ISSUE TITLE
Automatically resize image when it is too large

### ISSUE THREAD

**Issue by casouri** [yoshiharuyamashita/blackburn#71]
Here because my image is too large, it goes off screen.

It would be nice if images are automatically resized.

![screen shot 2018-04-26 at 1 23 52 am](https://user-images.githubusercontent.com/13118647/39287205-82576d0e-48f0-11e8-80bb-27fdccf0eda1.png)

**Comment by yoshiharuyamashita** [comment]
Hi @casouri 

Have you tried using [fluid_imgs](https://github.com/yoshiharuyamashita/blackburn#fluid_imgs)?

**Comment by casouri** [comment]
It works, thanks!

``` css
img {
    width: 100%;
    height: auto;
}
```
