### ISSUE TITLE
Two level menu

### ISSUE THREAD

**Issue by HTLife** [yoshiharuyamashita/blackburn#74]
I followed the instructions for making the two-level menu.
However, the menu could not be expand.  Is it the issue of blackburn theme?
```
  [[menu.main]]
    identifier = "brand"
    name = "brand"
    url = "/brands/"
    
    [[menu.main]]
        parent = "brand"
        name = "nike"
        url = "/brands/nike/"

    [[menu.main]]
        parent = "brand"
        name = "adidas"
        url = "/brands/adidas/"  
```

**Comment by david-j-m** [comment]
Hi, Having the same issue - did you find a solution?

**Comment by HTLife** [comment]
@david-j-m Unfortunately, I still have no idea.

**Comment by josephting** [comment]
Yes, it seems to be a bug of the theme.
I'll attempt to get it fixed when time allows.
