### ISSUE TITLE
suggestion: use pagination within section

### ISSUE THREAD

**Issue by emicklei** [yoshiharuyamashita/blackburn#8]
Thank you for creating this theme which I use to power http://ernestmicklei.com

I changed the pagination such that it will visit pages within a section

```
{{ if or (.PrevInSection) (.NextInSection) }}
<div class="prev-next-post pure-g">
  <div class="pure-u-1 pure-u-md-1-2">
    {{ if .PrevInSection }}
    <nav class="prev">
      <a href="{{ .PrevInSection.Permalink }}"><i class="fa fa-arrow-circle-left fa-fw fa-lg"></i>{{ .PrevInSection.Title }}</a>
    </nav>
    {{ end }}
  </div>
  <div class="pure-u-1 pure-u-md-1-2">
    {{ if .NextInSection }}
    <nav class="next">
      <a href="{{ .NextInSection.Permalink }}">{{ .NextInSection.Title }}<i class="fa fa-arrow-circle-right fa-fw fa-lg"></i></a>
    </nav>
    {{ end }}
  </div>
</div>
{{ end }}
```

Consider using this for people who have others sections than `post`

**Comment by yoshiharuyamashita** [comment]
Hi @emicklei

Thanks for your suggestion. I will look into it.

Cheers!

Yoshi

**Comment by yoshiharuyamashita** [comment]
Just found out about the following bug:

[.Next vs .NextInSection goes in opposite directions](https://github.com/spf13/hugo/issues/1061)

Hopefully it will be fixed in the next Hugo release.

Yoshi

**Comment by yoshiharuyamashita** [comment]
Done in #11
