### ISSUE TITLE
Home Page Broken with Hugo 0.57

### ISSUE THREAD

**Issue by recleev** [yoshiharuyamashita/blackburn#93]
I think this change in Hugo 0.57 renders the home page with only the post link as content.

> home.Pages now only returns pages in the top level section. Before this release, it included all regular pages in the site. This made it easy to list all the pages on home page, but it also meant that you needed to take special care if you wanted to navigate the page tree from top to bottom. If you need all regular pages, use .Site.RegularPages. Also see #6153.

I think I was able to resolve the issue by changing this line

`{{ range ( .Paginate (where .Data.Pages "Type" "post")).Pages }}`

in layouts/index.html to 

`{{ range ( .Paginate (where .Site.RegularPages "Type" "post")).Pages }}`

**Comment by MrCSharp22** [comment]
Confirmed this works. Can you PR this?

**Comment by recleev** [comment]
Yeah. Pull request is up [here](https://github.com/yoshiharuyamashita/blackburn/pull/94).
